stages:
  - setup
  - tests

setup_venv:
  stage: setup
  script:
    - python -m venv env
    - ./env/Scripts/activate
    - pip install pytest
    - pip install psutil
  allow_failure: true

test:
  stage: tests
  dependencies:
    - setup_venv
  script:
    - ./env/Scripts/activate
    - cd ../../tests
    - pytest -s
  allow_failure: true