stages:
  - build
  - setup
  - tests
  - deploy

build_package:
  stage: build
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  allow_failure: true
  artifacts:
    paths:
      - ./dist/*.whl
    expire_in: 1 week

setup_venv:
  stage: setup
  script:
    - pip install twine
    - cd tests/
    - python -m venv env
    - ./env/Scripts/activate
    - pip install pytest
    - pip install pytest-cov
    - pip install ../dist/cw_dcp-0.1-py3-none-any.whl
  allow_failure: true
  artifacts:
    paths:
      - ./tests/env
    expire_in: 1 week

test:
  stage: tests
  dependencies:
    - setup_venv
  script:
    - cd tests/
    - ./env/Scripts/activate
    - pytest -s --junitxml=results/run_tests.xml --cov-report term --cov-report xml:coverage.xml --cov=cw_dcp
    - sonar-scanner.bat -D"sonar.projectKey=cw_dcp" -D"sonar.sources=env/Lib/site-packages/cw_dcp" -D"sonar.host.url=$SQ_URL" -D"sonar.login=$SQ_TOKEN" -D"sonar.scm.disabled=true"
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit: tests/results/run_tests.xml
    paths:
      - tests/results/
      - tests/*.xml

deployment:
  stage: deploy
  dependencies:
    - build_package
    - setup_venv
  script:
    - ./tests/env/Scripts/activate
    - cd ./dist/
    - twine upload *.whl --repository-url https://nexus.codewerk.de/repository/pypi-codewerk/ -u $USER -p $PASSWORD
  allow_failure: true

