include:
  project: 'shacks/python/pyshacks_ci_config'
  file: 'pyshack.gitlab-ci.yml'

default:
    tags:
        - pcap
        - windows

stages:
  - build
  - setup
  - tests
  - analyse
  - deploy
  - pages

pages:
  stage: pages
  tags:
      - docker
      - linux
  image:
    name: pandoc/alpine
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir -p public
    - echo '<meta name="google-site-verification" content="ooqaohCgAywtsa97hQcmfXVsc5ZlgQaKSnXvTkSSLGE" />' > header.html
    - pandoc -f markdown -t html -s README.md -o public/index.html --metadata title="PNIO-DCP" --metadata keywords=python,dcp,profinet -H header.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]$/'
      when: on_success
      allow_failure: false
    - when: manual
      allow_failure: true
