stages:
  - build
  - setup
  - tests

build_package:
  stage: build
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  allow_failure: true
  artifacts:
    paths:
      - ./dist/*.whl
    expire_in: 1 week

setup_venv:
  stage: setup
  script:
    - python -m venv env
    - ./env/Scripts/activate
    - pip install pytest
    - pip install pytest-cov
    - pip install ./dist/cw_dcp-0.1-py3-none-any.whl
  allow_failure: true
  artifacts:
    paths:
      - ./env
    expire_in: 1 week

test:
  stage: tests
  dependencies:
    - setup_venv
  script:
    - ./env/Scripts/activate
    - cd tests
    - pytest -s --junitxml=results/tests.xml --cov-report term --cov-report xml:coverage.xml --cov=cw_dcp
    - sonar-scanner.bat -D"sonar.projectKey=$SQ_PRODUCT_KEY" -D"sonar.sources=../env/Lib/site-packages/cw_dcp" -D"sonar.host.url=$SQ_URL" -D"sonar.login=$SQ_TOKEN" -D"sonar.scm.disabled=true"
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit: tests/results/tests.xml
    paths:
      - tests/results/
      - tests/*.xml

