include:
  - project: 'shacks/python/pyshacks_ci_config'
    file: 'pyshack.gitlab-ci.yml'
  - local: 'public.gitlab-ci.yml'

default:
    tags:
        - pcap
        - windows

stages:
  - build
  - setup
  - tests
  - analyse
  - deploy
  - pages
  - pypi

pages:
  stage: pages

deploy_pypi:
  stage: pypi
