# image: python:latest

stages:
  - setup
  - tests

setup_venv:
  stage: setup
  script:
    - venv env
    - env/Scripts/activate
    - pip install pytest
    - pip install psutil

test:
  stage: tests
  dependencies:
    - setup_venv
  script:
    - cd tests/
    - ./env/Scripts/activate
    - pytest -s
  allow_failure: true